
# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"
  ignore = "false" # Prevent ignoring builds

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set Cache-Control headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure environment variables are available during build
[build.environment]
  NODE_VERSION = "18"
